### ISSUE TITLE
如何使用这个插件

### ISSUE THREAD

**Issue by 1111mp** [wuyunqiang/react-native-pullview#8]
我一开始是使用react-native-pull的 但是出现了下滑卡顿的现象 然后就找到你这边来了 看了一下源码 你这边做了很大的改动 但是我npm install react-native-pullView的时候 包里面的代码跟之前的一样的 请问是不是直接吧你这里的文件下载下来用呢？我的项目有两个地方需要用到 一个是下拉刷新 另一个是下拉刷新和底部加载  但是我不知道你这里是不是解决了滑动卡顿的问题  而且对于你这里的用法我也是不清楚 还希望您能解答一下

**Comment by fantasy525** [comment]
同问，这个怎么使用？

**Comment by fantasy525** [comment]
> 我一开始是使用react-native-pull的 但是出现了下滑卡顿的现象 然后就找到你这边来了 看了一下源码 你这边做了很大的改动 但是我npm install react-native-pullView的时候 包里面的代码跟之前的一样的 请问是不是直接吧你这里的文件下载下来用呢？我的项目有两个地方需要用到 一个是下拉刷新 另一个是下拉刷新和底部加载 但是我不知道你这里是不是解决了滑动卡顿的问题 而且对于你这里的用法我也是不清楚 还希望您能解答一下

你现在是怎么解决的
